# Generated by Django 5.0.3 on 2024-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
